### ISSUE TITLE
Determine slot from within firmware

### ISSUE THREAD

**Issue by dgorski** [tjboldt/ProDOS-ROM-Drive#1]
I ran across this project (ProDOS-ROM-Drive) of yours while researching my own apple2 IO board project.

During my reasearch I found this article from Apple which contains code that can determine the slot number it is executing from.  I thought this could be of interest for this project or your other project (Apple2-IO-RPi).

[Apple II Hobby and Prototyping Board Manual](https://www.apple.asimov.net/documentation/hardware/io/Apple%20II%20Hobby%20and%20Prototyping%20Board%20Manual.pdf)

The relevant code is at the bottom of page 6.  Hope this is useful, keep up the good work!

- Darrin

**Comment by tjboldt** [comment]
Thanks for the link. That’s a great resource. I am already doing something similar in my [other project](https://github.com/tjboldt/Apple2-IO-RPi) but I found it easier for both projects to simply use a separate 256 bytes of firmware for each slot and use the address lines to access it. This allows jumps to subroutines (JSR) within the firmware which is difficult to do otherwise in 6502 assembler with relative code.

**Comment by tjboldt** [comment]
Reopening as more than one person has asked about making this relative code. It's not necessary to make the card work but could reduce the wasted space for firmware and allow for a few extra blocks on the ProDOS volume.

**Comment by rallepalaveev** [comment]
Hi I am using this address self-determining code in the firmware I use for my cards posted on my profile. :)

**Comment by rallepalaveev** [comment]
Hi, just a heads up - I programmed the relative code for the ROM drive in a simulator, I only need to test it on the real hardware, which I'd do over the Christmas break, then I'll share. Happy holidays!

**Comment by Daniel102010** [comment]
Thanks for let me know, Happy Christmas 🎄 and Happy Holiday. Regards Daniel 


Sent from Yahoo Mail for iPhone


On Saturday, December 4, 2021, 9:39 a.m., Ralle Palaveev ***@***.***> wrote:




Hi, just a heads up - I programmed the relative code for the ROM drive in a simulator, I only need to test it on the real hardware, which I'd do over the Christmas break, then I'll share. Happy holidays!

**Comment by tjboldt** [comment]
If you submit a PR, I can test the firmware changes for you.

**Comment by rallepalaveev** [comment]
Sure, here it is. Let me know if it wor
[BlankDriveWithFirmware-RP-patch.zip](https://github.com/tjboldt/ProDOS-ROM-Drive/files/7653800/BlankDriveWithFirmware-RP-patch.zip)
ks

**Comment by tjboldt** [comment]
It would be more interesting to wire it up so that it reads the firmware from block $0001 instead of block $0800. Block $0001 is reserved for Apple /// SOS and not used by ProDOS so the firmware could reside there instead.

**Comment by rallepalaveev** [comment]
I can do that, but it would require hardware changes too. The two 74LS245 buffers must be wired such that they address $200-$2FF of the EPROM upon I/O Select active. All bits of the high byte go low and on the low byte - bits 0-3 to A0-A3, bits 4,6,7 to ground and bit 5 to power. And the firmware should work as it is now from there. Provided that there are no bugs and it is functional, as I have not tested it yet.

**Comment by tjboldt** [comment]
I burned your firmware patch onto an EPROM and tested the card. It does indeed work. Thanks. I am going to make some physical modifications to a spare board to see if it will work placing the code in block $0001, effectively freeing the entire EPROM for use as a drive. If you want to have credit for your work, fork the project and submit a pull request. When I merge, you will appear as one of the contributors of this project. Likely there will be a v3.0 of this board coming.

**Comment by rallepalaveev** [comment]
Hi, I am glad it worked! I would be expecting the newly wired card - v3.0, take care!

**Comment by tjboldt** [comment]
Firmware patch has been merged into the repo. Additional enhancements to hardware and updating firmware source will be done separately. Closing this issue.
