### ISSUE TITLE
Crashing with error on bootup

### ISSUE THREAD

**Issue by StormTrooper** [tjboldt/ProDOS-ROM-Drive#12]
I'm having issues getting this to boot and wondering if you are able to point me in the right direction. 

I've build one of these cards and have written the GamesWithFirmware.po to a 27C801 and verified ok. Have also tested all the logic chips and double checked my soldering - all good.

When I bootup the computer ProDOS starts but it crashes with a error on startup.

![Screenshot from 2022-07-06 20-24-36](https://user-images.githubusercontent.com/1429043/177627297-01697fcc-f372-49f0-a9e6-a5111d0bffb3.png)

I don't have access to a disk drive to test a normal bootup but have run the internal diagnostics (Apple iie Enhanced) and get the system ok.

**Comment by StormTrooper** [comment]
Ver 4 with the v4 firmware.

**Comment by tjboldt** [comment]
I’ll assume all 0.1 uF capacitors are in place? A bad or missing cap will do that too. Have you tried the card in other slots? And of course always power off the computer when adding or removing cards. You probably know all this though given your skill level soldering and testing components.

**Comment by StormTrooper** [comment]
Yes, all the caps are in place.  I've tried the card in other slots and still experience the same issue. Not really sure what to check next. I've retested the logic chips and they are all ok. 

At first I suspected a faulty RAM Chip on the Apple but it passes the internal diag test.

**Comment by tjboldt** [comment]
Do you have an extended 80 column card installed? The person who helped create the relocatable version of the firmware noted that ProDOS was failing to boot with only 64 KB of RAM instead of 128 KB. He has a fix but I haven't had time to integrate and test it.

**Comment by StormTrooper** [comment]
I have a Saturn 128k extended card as well as another extended 80 col card. Tried each one - didn't make any difference.

**Comment by StormTrooper** [comment]
I've also got a Apple IIe diagcard and run the ram test on loop and there are no failures. 

Have also build another card with different components and still getting the same error so am really out of ideas now.

**Comment by tjboldt** [comment]
I believe this may be a firmware bug. There is a new firmware in the works that should be ready to test this week.

**Comment by tjboldt** [comment]
@StormTrooper can you pull from the `firmware-fix` branch and try that image? I made some changes based on recommendations from @rallepalaveev plus a few other tweaks. It works on my machine now even with the extended 80 column card removed.

**Comment by StormTrooper** [comment]
Great stuff. I can confirm it's working for me as well. 

Thanks
