### ISSUE TITLE
Key to skip slot during boot

### ISSUE THREAD

**Issue by Alex-Kw** [tjboldt/ProDOS-ROM-Drive#14]
I'm wondering if the firmware could be modified to have a skip on boot key, similar to the MicroDrive or a recent patch for the Dan ][ SD card. For reference:

https://www.applefritter.com/comment/99467#comment-99467

Being able to hold escape or a different key during poweron to skip the ROM drive would be a very useful feature. Thanks for your consideration.

**Comment by tjboldt** [comment]
That is a good idea although note that it will only work when the RPi is connected since the firmware address selection is controlled by 3.3V powered chips. I can add this to the next firmware release.

**Comment by Alex-Kw** [comment]
Terence, 

In this case I'm referring to a ProDOS Rom drive in Slot 7 (for example) of a real machine, with a normal Apple disk controller in slot 6. Normally the card in slot 7 would take precedence, but the suggestion is that holding escape or another key on the Apple IIe / IIgs during poweron would skip the ProDOS ROM Drive and proceed to Floppy drives or the other slots. I do know the MicroDrive turbo which acts in this manner has 2 separate firmwares but I don't know if this feature is coded differently in the two versions (Apple II vs IIGS firmware).

**Comment by tjboldt** [comment]
Hi Alex,

Sorry, I was replying from my phone and thought this was my other project. For this project, it should be relatively simple to add the ESC to skip boot. Note that it boots very fast so you'd probably need to hold ESC while booting. I'll try and have a firmware change in sometime in the next week or so.

**Comment by Alex-Kw** [comment]
Of course, no problem, and thank you. 

And to echo, I agree that It would be expected to have to already have the ESC key down on boot, as like you said, the boot sequence is extremely fast. 

Cheers
